type Schedule {
  _id: String!
  category: String!
  where: String!
  when: When!
  who: Who!
  memo: String
  group: String
}

type Where {
  place: String!
}

type When {
  year: String!
  month: String!
  date: String!
  startTime: String!
}

type Who {
  host: String!
  guest: [Guest]!
}

type Guest {
  nickname: String!
  record: [Record]!
}

type Record {
  level: String!
  count: Int!
}

input ScheduleId {
  _id: String!
}

input CreateScheduleInput {
  email: String!
  category: String!
  where: String!
  when: WhenInput!
  who: WhoInput!
  memo: String
  group: String
}

input DeleteScheduleInput {
  email: String!
  _id: String!
}

input EditScheduleInput {
  email: String!
  _id: String!
  category: String!
  where: String!
  when: WhenInput!
  who: WhoInput!
  memo: String
  group: String
}

input InviteScheduleInput {
  email: String!
  _id: String!
  nickname: String!
}

input JoinScheduleInput {
  email: String!
  _id: String!
  nickname: String!
}

input EditRecordInput {
  email: String!
  _id: String!
  nickname: String!
  record: [RecordInput]!
}

input WhereInput {
  place: String!
}

input WhenInput {
  year: String!
  month: String!
  date: String!
  startTime: String!
}

input WhoInput {
  host: String!
  guest: [GuestInput]!
}

input GuestInput {
  nickname: String!
  record: [RecordInput]!
}

input RecordInput {
  level: String!
  count: Int!
}

type Query {
  getAllSchedule(schedule: UserEmail): [Schedule]!
  getScheduleDetail(schedule: ScheduleId): Schedule
}

type Mutation {
  createSchedule(schedule: CreateScheduleInput): Schedule!
  deleteSchedule(schedule: DeleteScheduleInput): Message!
  editSchedule(schedule: EditScheduleInput): Schedule!
  inviteSchedule(schedule: InviteScheduleInput): Schedule!
  joinSchedule(schedule: JoinScheduleInput): Schedule!
  editRecord(schedule: EditRecordInput): Schedule!
}
