type User {
  email: String!
  nickname: String!
  myGroupList: [String]
  myRecord: [MyRecord]
}

type MyRecord {
  spotName: String!
  records: [Record]!
}

type Record {
  level: String!
  nameOrColor: String
  count: Int!
}

input RecordInput {
  level: String!
  nameOrColor: String
  count: Int!
}

type Spot {
  _id: String
  spotName: String!
  spotBranch: String!
  address: String!
  phase: [Phase]!
  category: [String]!
}

type Phase {
  level: String!
  nameOrColor: String!
}

type Schedule {
  _id: String
  category: [String]!
  when: String!
  where: String!
  host: String!
  guest: [Guest]!
  memo: String!
  group: String!
}

type Guest {
  nickname: String!
  record: [Record]!
}

input GuestInput {
  nickname: String!
  record: [RecordInput]!
}

type Group {
  _id: String
  gname: String!
  leader: String!
  createdAt: String!
  description: String!
  memberList: [String]!
  mainCatecory: String!
  age: [Int]!
  secret: Boolean!
  password: String
  schedules: [Schedule]!
  join: Boolean!
}

type Result {
  success: Boolean!
}

input UserInput {
  email: String
  nickname: String
}

input EditRecordInput {
  email: String!
  _id: String!
  record: [RecordInput]!
}

input CreateScheduleInput {
  email: String!
  category: [String]!
  when: String!
  where: String!
  host: String!
  guest: [GuestInput]!
  memo: String!
  group: String!
}

input EditScheduleInput {
  _id: String!
  email: String!
  category: [String]!
  when: String!
  where: String!
  host: String!
  guest: [GuestInput]!
  memo: String!
  group: String!
}

input CreateGroupInput {
  email: String!
  gname: String!
  leader: String!
  createdAt: String!
  description: String!
  mainCatecory: String!
  age: [Int]!
  secret: Boolean!
  password: String
}

input EditGroupInput {
  _id: String!
  email: String!
  gname: String!
  leader: String!
  createdAt: String!
  description: String!
  mainCatecory: String!
  age: [Int]!
  secret: Boolean!
  password: String
}

type Query {
  getMyPage(email: String): User!
  getAllUser: [User]!

  getMySchedule(email: String): [Schedule]!
  getScheduleDetail(_id: String): Schedule!

  getAllSpot: [Spot!]!
  getSpotDetail(spotId: String): Spot!

  checkDuplicateGroupName(gname: String): Result!
  getAllGroup: [Group]!
  getMyGroup(email: String): [Group]!
  getGroupDetail(_id: String): Group!
  openSecretGroup(_id: String, password: String): Group!
}

type Mutation {
  login(userInfo: UserInput): User!
  setNickname(userInfo: UserInput): User!
  deleteUser(email: String): Result!

  createSchedule(schedule: CreateScheduleInput): Schedule!
  editSchedule(schedule: EditScheduleInput): Schedule!
  deleteSchedule(_id: String, email: String): Result!
  joinSchedule(_id: String, email: String): Schedule!
  comeoutSchedule(_id: String, email: String): Schedule!
  inviteSchedule(_id: String, email: String, guest: String): Schedule!

  editRecord(records: RecordInput): Schedule!

  createGroup(group: CreateGroupInput): Group!
  editGroup(group: EditGroupInput): Group!
  joinGroup(_id: String, email: String): Group!
  leaveGroup(_id: String, email: String): Group!
  deleteGroup(_id: String, email: String): Result!
  changeLeader(_id: String, email: String, newLeader: String): Group!
}
