type Schedule {
  _id: String!
  category: [String!]!
  where: String!
  when: String!
  who: Who!
  memo: String
  group: String
}

type Who {
  host: String!
  guest: [Guest]!
}

type Guest {
  nickname: String!
  record: [Record]!
}

type Record {
  level: String!
  count: Int!
}

input ScheduleId {
  _id: String!
}

input CreateScheduleInput {
  email: String!
  category: [String!]!
  where: String!
  when: String!
  who: WhoInput!
  memo: String
  group: String
}

input DeleteScheduleInput {
  email: String!
  _id: String!
}

input EditScheduleInput {
  email: String!
  _id: String!
  category: [String!]!
  where: String!
  when: String!
  who: WhoInput!
  memo: String
  group: String
}

input JoinScheduleInput {
  _id: String!
  nickname: String!
}

input InviteScheduleInput {
  _id: String!
  nickname: String!
}

input EditRecordInput {
  email: String!
  _id: String!
  nickname: String!
  record: [RecordInput]!
}

input WhoInput {
  host: String!
  guest: [GuestInput]!
}

input GuestInput {
  nickname: String!
  record: [RecordInput]!
}

input RecordInput {
  level: String!
  count: Int!
}

input ComeoutScheduleInput {
  email: String!
  _id: String!
}

type Query {
  getAllSchedule(schedule: UserEmail): [Schedule]!
  getGroupSchedule(schedule: UserEmail): [Schedule]!
  getScheduleDetail(schedule: ScheduleId): Schedule
}

type Mutation {
  createSchedule(schedule: CreateScheduleInput): Schedule!
  deleteSchedule(schedule: DeleteScheduleInput): Message!
  editSchedule(schedule: EditScheduleInput): Schedule!
  joinSchedule(schedule: JoinScheduleInput): Schedule!
  inviteSchedule(schedule: InviteScheduleInput): Schedule!
  comeoutSchedule(schedule: ComeoutScheduleInput): Message!
  editRecord(schedule: EditRecordInput): Schedule!
}
