type User {
  email: String!
  nickname: String!
  myGroupList: [String]
}

type Message {
  value: String
}

input UserEmail {
  email: String!
}

input LoginInput {
  email: String!
  nickname: String!
}

input NicknameInput {
  email: String!
  nickname: String!
}

type Query {
  getMyPage(user: UserEmail): User
}

type Mutation {
  login(user: LoginInput): User!
  setNickname(user: NicknameInput): User!
  deleteUser(user: UserEmail): Message
}
